services:
  postgres:
    image: postgres:16
    container_name: postgres-pizza-db
    environment:
      POSTGRES_DB: pizza_db
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analystpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analyst"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
